version: "3"
services:
  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kfapplication
    ports:
      - 3306:3306
      - 33060:33060

  kfapp:
    image: kfapp:0.1.0
    restart: always
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://db:3306/kfapplication?allowPublicKeyRetrieval=true&useSSL=false
      JDBC_DATABASE_USER: root
      JDBC_DATABASE_PASSWORD: root
      KAFKA_SERVER: kafka:9092
    ports:
      - 80:8080
    depends_on:
      - db
      - kafka

  kfmailsender:
    image: kfmailsender:0.1.0
    restart: always
    environment:
      MAIL_SENDER_USERNAME: user
      MAIL_SENDER_PASSWORD: password
      KAFKA_SERVER: kafka:9092
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 22181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROCKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 29092:29092
    depends_on:
      - zookeeper